/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pages;

import java.io.FileWriter;
import java.io.IOException;
import java.lang.Thread;
import javax.swing.*;

/**
 *
 * @author Danial Suhail
 */
public class FormThree extends javax.swing.JPanel {

    /**
     * Creates new form FormOne
     */
    public FormThree(int index) {
        initComponents();
        setOpaque(false);
        jLabel3.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new swings.RoundPanel();
        StockDataButton = new javax.swing.JButton();
        StockGraphButton = new javax.swing.JButton();
        tickerSymbolGetter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        requestIMG = new javax.swing.JLabel();

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel1.setPreferredSize(new java.awt.Dimension(745, 487));

        StockDataButton.setText("Stock Data");
        StockDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockDataButtonActionPerformed(evt);
            }
        });

        StockGraphButton.setText("Stock Graph");
        StockGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockGraphButtonActionPerformed(evt);
            }
        });

        tickerSymbolGetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tickerSymbolGetterActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jLabel2.setText("Ticker Symbol");

        jLabel1.setText("Input a ticker symbol of a stock and select one of the buttons");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Stock Market Simulator");

        requestIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/8725582_chart_line_icon.png"))); // NOI18N

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(tickerSymbolGetter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel2))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addComponent(StockDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(StockGraphButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(requestIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tickerSymbolGetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StockDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StockGraphButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(requestIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void StockGraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockGraphButtonActionPerformed
         jLabel3.setText(tickerSymbolGetter.getText());
        String tickSymbol = jLabel3.getText();

        // Create a new JFrame to host the StockGrapher panel
        JFrame graphFrame = new JFrame("Stock Graph for " + tickSymbol);
        graphFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        // Add the StockGrapher panel to the JFrame
        StockGrapher sgPanel = new StockGrapher(tickSymbol);
        graphFrame.add(sgPanel);
        
        // Set the size and make the JFrame visible
        graphFrame.setSize(800, 600);
        graphFrame.setVisible(true);
    }//GEN-LAST:event_StockGraphButtonActionPerformed

    private void StockDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockDataButtonActionPerformed
        jLabel3.setText(tickerSymbolGetter.getText());
        String tickSymbol = jLabel3.getText();
       
         
       StockMarketSimulatorUI smsUI = new StockMarketSimulatorUI(tickSymbol); // ticker symbol as a String
        smsUI.show();
        
    }//GEN-LAST:event_StockDataButtonActionPerformed

    private void tickerSymbolGetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tickerSymbolGetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tickerSymbolGetterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StockDataButton;
    private javax.swing.JButton StockGraphButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel requestIMG;
    private swings.RoundPanel roundPanel1;
    private javax.swing.JTextField tickerSymbolGetter;
    // End of variables declaration//GEN-END:variables
}
