package pages;


import java.util.List;
import org.json.JSONException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class StockMarketSimulatorUI extends javax.swing.JFrame {

    public static String tickerSymbol = "";
    
    
    /**
     * Creates new form WhyDontThisWork
     */
    public StockMarketSimulatorUI(String symbol) {
        initComponents();
        tickerSymbol = symbol;
        
        
        String apiKey = "394YWOGE00QS4ANO"; // or input another API key from the AlphaVantage website if this one no longer works

        AlphaVantageAPI api = new AlphaVantageAPI();
        String jsonResponse = api.getStockData(apiKey, tickerSymbol);

        if (jsonResponse != null) {
            try {
                StockDataParser.parseStockData(jsonResponse);

                // Display the #th page of stock data -> use a variable to indicate page #
                List<String> stockSection = StockDataParser.getStockSection(1);
                stockLineLabel1.setText(stockSection.get(0));
                stockLineLabel2.setText(stockSection.get(1));
                stockLineLabel3.setText(stockSection.get(2));
                stockLineLabel4.setText(stockSection.get(3));
                stockLineLabel5.setText(stockSection.get(4));
                stockLineLabel6.setText(stockSection.get(5));
                stockLineLabel7.setText(stockSection.get(6));
                stockLineLabel8.setText(stockSection.get(7));
                stockLineLabel9.setText(stockSection.get(8));
                stockLineLabel10.setText(stockSection.get(9));

            } catch (JSONException e) {
                e.printStackTrace();
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        stockLineLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        stockLineLabel2 = new javax.swing.JLabel();
        stockLineLabel3 = new javax.swing.JLabel();
        stockLineLabel4 = new javax.swing.JLabel();
        stockLineLabel5 = new javax.swing.JLabel();
        stockLineLabel6 = new javax.swing.JLabel();
        stockLineLabel7 = new javax.swing.JLabel();
        stockLineLabel8 = new javax.swing.JLabel();
        stockLineLabel9 = new javax.swing.JLabel();
        stockLineLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setText("Stock Market Simulator");

        stockLineLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockLineLabel1.setText("Stock Data Row 1");

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        stockLineLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockLineLabel2.setText("Stock Data Row 2");

        stockLineLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockLineLabel3.setText("Stock Data Row 3");

        stockLineLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockLineLabel4.setText("Stock Data Row 4");

        stockLineLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockLineLabel5.setText("Stock Data Row 5");

        stockLineLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockLineLabel6.setText("Stock Data Row 6");

        stockLineLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockLineLabel7.setText("Stock Data Row 7");

        stockLineLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockLineLabel8.setText("Stock Data Row 8");

        stockLineLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockLineLabel9.setText("Stock Data Row 9");

        stockLineLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stockLineLabel10.setText("Stock Data Row 10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stockLineLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(Title))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 223, Short.MAX_VALUE))
                    .addComponent(stockLineLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockLineLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockLineLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockLineLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockLineLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockLineLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockLineLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockLineLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockLineLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stockLineLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockLineLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockLineLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockLineLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockLineLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockLineLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockLineLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockLineLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockLineLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockLineLabel10)
                .addGap(18, 18, 18)
                .addComponent(BackButton)
                .addGap(180, 180, 180))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockMarketSimulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockMarketSimulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockMarketSimulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockMarketSimulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockMarketSimulatorUI(tickerSymbol).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel stockLineLabel1;
    private javax.swing.JLabel stockLineLabel10;
    private javax.swing.JLabel stockLineLabel2;
    private javax.swing.JLabel stockLineLabel3;
    private javax.swing.JLabel stockLineLabel4;
    private javax.swing.JLabel stockLineLabel5;
    private javax.swing.JLabel stockLineLabel6;
    private javax.swing.JLabel stockLineLabel7;
    private javax.swing.JLabel stockLineLabel8;
    private javax.swing.JLabel stockLineLabel9;
    // End of variables declaration//GEN-END:variables
}
