/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import events.EventMenu;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import pages.FormOne;
import pages.FormTwo;
import pages.FormThree;
import pages.FormFour;
import pages.FormMain;
import components.Balance;

/**
 *
 * @author Danial Suhail
 */
public class mainMenu extends javax.swing.JFrame {
private int hour;
private int minute;
public static int timeCounter=0;
private int second;
private int csecond;
private boolean isStart;
    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
                
        this.setTitle("SmartVault");
        
        this.setSize(1000,625);
        
        this.setResizable(false);
        
        Image icon = new ImageIcon(this.getClass().getResource("/icons/CardLogoV1.png")).getImage();
        this.setIconImage(icon);
        
                isStart=true;
    try {
        FileWriter myFl = new FileWriter("voucherPrice", false);
    } catch (IOException ex) {
        Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
    }
        Thread th = new Thread() {
            public void run() {
                while(isStart==true) {
                    try {
                        sleep(10);
                    csecond++;
                    if (csecond == 60) {
                     second++;
                     csecond=0;
                }
                if (second==60){
                minute++;
                timeCounter++;
                Balance.currentSaving += (Balance.currentSaving*0.01);
                second = 0;
                }
                minuteLbl.setText("" + minute);

                } 
                catch (Exception ex) {
                    System.out.println("Something wrong has occured!");
                    }
                }
            }
        };th.start();

        EventMenu event = new EventMenu() {
            @Override
            public void selected(int index) {
                
                if(index == 0) {
                    showForm(new FormMain());
                } else if (index == 1) {
                    showForm(new FormOne(index));
                } else if (index == 2) {
                    showForm(new FormTwo(index));
                } else if (index == 3) { 
                    showForm(new FormThree(index));
                } else if (index == 4) { 
                    try {
                        try {
                            //System.out.println(System.getProperty("user.dir"));
                            System.out.println(minute);
                            FileWriter myWriter = new FileWriter("qrStorage.txt", true);
                            myWriter.write(minute + "\n");
                            myWriter.close();
                         } catch (IOException e) {
                            System.out.println("An error occurred.");
                            e.printStackTrace();
                         }
                        showForm(new FormFour(index));
                    } catch (IOException ex) {
                        Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                else if (index == 5) {
                   System.out.println("Logout");
                   System.exit(0);
                   // Figure out how to log user out of account by quitting out of application and showing the login form.
                } else {
                }
            }   
        };
        menu1.initMenu(event);
        showForm(new FormMain());
        
    }
    
    private void showForm(Component com) {
        formBody.removeAll();
        formBody.add(com);
        formBody.revalidate();
        formBody.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formBody = new javax.swing.JPanel();
        topBar1 = new components.TopBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roundPanel1 = new swings.RoundPanel();
        minuteLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menu1 = new components.Menu();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 625));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 625));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formBody.setBackground(new java.awt.Color(223, 230, 234));
        formBody.setLayout(new java.awt.BorderLayout());
        jPanel1.add(formBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 73, 770, 552));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SmartVaultIconV1.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CardLogoV1.png"))); // NOI18N

        minuteLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minuteLbl.setText("0");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("min");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(minuteLbl)
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minuteLbl)
                    .addComponent(jLabel2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout topBar1Layout = new javax.swing.GroupLayout(topBar1);
        topBar1.setLayout(topBar1Layout);
        topBar1Layout.setHorizontalGroup(
            topBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBar1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topBar1Layout.setVerticalGroup(
            topBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBar1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(topBar1Layout.createSequentialGroup()
                .addGroup(topBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(topBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 0, 770, 70));
        jPanel1.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 210, 590));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel formBody;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private components.Menu menu1;
    private javax.swing.JLabel minuteLbl;
    private swings.RoundPanel roundPanel1;
    private components.TopBar topBar1;
    // End of variables declaration//GEN-END:variables
}
